<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payments Management Report</title>
    <style>
        @page { size: A4; margin: 1cm; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.4; margin: 0; padding: 0; background: white; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        .header h1 { margin: 0; font-size: 24px; text-transform: uppercase; letter-spacing: 2px; }
        .header p { margin: 5px 0 0; font-size: 10px; text-transform: uppercase; color: #666; font-weight: bold; }
        .summary-box { display: flex; gap: 20px; margin-bottom: 20px; }
        .summary-card { flex: 1; border: 1px solid #eee; padding: 15px; border-radius: 8px; background: #fafafa; }
        .summary-card p { margin: 0; font-size: 9px; text-transform: uppercase; color: #666; font-weight: 900; }
        .summary-card h2 { margin: 5px 0 0; font-size: 20px; color: #3b82f6; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 10px; }
        th { background: #f4f4f4; border: 1px solid #ddd; padding: 10px; text-align: left; text-transform: uppercase; font-weight: 900; }
        td { border: 1px solid #ddd; padding: 8px; vertical-align: middle; }
        .text-center { text-align: center; }
        .text-right { text-align: right; }
        .status-paid { color: #1d4ed8; font-weight: bold; }
        .status-pending { color: #3b82f6; font-weight: bold; }
        .status-rejected { color: #2563eb; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 9px; text-align: right; color: #999; }
        @media print {
            .no-print { display: none; }
            body { -webkit-print-color-adjust: exact; }
        }
    </style>
</head>
<body onload="window.print()">
    <div class="no-print" style="background: #f8fafc; padding: 10px; border-bottom: 1px solid #eee; text-align: center; font-size: 12px; font-weight: bold;">
        Tip: Set your printer destination to "Save as PDF" to generate a PDF file.
    </div>

    <div class="header">
        <h1>Collections & Payments Summary</h1>
        <p>Official Financial Transaction Registry Report</p>
    </div>

    <div class="summary-box">
        <div class="summary-card">
            <p>Total Collection (Paid)</p>
            <h2>₱ {{ number_format($totalAmount, 2) }}</h2>
        </div>
        <div class="summary-card">
            <p>Total Records</p>
            <h2 style="color: #333;">{{ count($payments) }}</h2>
        </div>
        <div class="summary-card" style="text-align: right;">
            <p>Report Date</p>
            <h2 style="color: #666; font-size: 16px;">{{ date('M d, Y') }}</h2>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Student Name</th>
                <th>Program / Level</th>
                <th>Method</th>
                <th>Reference No.</th>
                <th>Date</th>
                <th class="text-center">Status</th>
                <th class="text-right">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($payments as $payment)
                <tr>
                    <td style="color: #888;">#{{ str_pad($payment->id, 6, '0', STR_PAD_LEFT) }}</td>
                    <td style="font-weight: bold; text-transform: uppercase;">{{ optional($payment->user)->name ?? 'Unknown' }}</td>
                    <td>
                        {{ optional($payment->application)->course_code ?? 'N/A' }}
                        <br>
                        <span style="font-size: 8px; color: #888;">{{ optional($payment->application)->year_level }}</span>
                    </td>
                    <td>{{ $payment->payment_method ?? 'Cash' }}</td>
                    <td style="text-transform: uppercase;">{{ $payment->transaction_id }}</td>
                    <td>{{ $payment->created_at->format('M d, Y') }}</td>
                    <td class="text-center">
                        <span class="status-{{ strtolower($payment->status) }}">
                            {{ $payment->status }}
                        </span>
                    </td>
                    <td class="text-right" style="font-weight: bold; font-size: 11px;">
                        ₱ {{ number_format($payment->amount, 2) }}
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Financial Management System — {{ date('h:i A') }}
    </div>
</body>
</html>
